// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_login.proto

package com.tw.login.proto;

public final class CsLogin {
  private CsLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSLoginInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string UserName = 1;
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string Password = 2;
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.tw.login.proto.CSLoginInfo}
   */
  public static final class CSLoginInfo extends
      com.google.protobuf.GeneratedMessage
      implements CSLoginInfoOrBuilder {
    // Use CSLoginInfo.newBuilder() to construct.
    private CSLoginInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSLoginInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSLoginInfo defaultInstance;
    public static CSLoginInfo getDefaultInstance() {
      return defaultInstance;
    }

    public CSLoginInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tw.login.proto.CsLogin.CSLoginInfo.class, com.tw.login.proto.CsLogin.CSLoginInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<CSLoginInfo> PARSER =
        new com.google.protobuf.AbstractParser<CSLoginInfo>() {
      public CSLoginInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string UserName = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object userName_;
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string UserName = 1;</code>
     *
     * <pre>
     *’À∫≈
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Password = 2;</code>
     *
     * <pre>
     *√‹¬Î
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userName_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tw.login.proto.CsLogin.CSLoginInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tw.login.proto.CSLoginInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tw.login.proto.CsLogin.CSLoginInfo.class, com.tw.login.proto.CsLogin.CSLoginInfo.Builder.class);
      }

      // Construct using com.tw.login.proto.CsLogin.CSLoginInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginInfo_descriptor;
      }

      public com.tw.login.proto.CsLogin.CSLoginInfo getDefaultInstanceForType() {
        return com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance();
      }

      public com.tw.login.proto.CsLogin.CSLoginInfo build() {
        com.tw.login.proto.CsLogin.CSLoginInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tw.login.proto.CsLogin.CSLoginInfo buildPartial() {
        com.tw.login.proto.CsLogin.CSLoginInfo result = new com.tw.login.proto.CsLogin.CSLoginInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tw.login.proto.CsLogin.CSLoginInfo) {
          return mergeFrom((com.tw.login.proto.CsLogin.CSLoginInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tw.login.proto.CsLogin.CSLoginInfo other) {
        if (other == com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tw.login.proto.CsLogin.CSLoginInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tw.login.proto.CsLogin.CSLoginInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string UserName = 1;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string UserName = 1;</code>
       *
       * <pre>
       *’À∫≈
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string Password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       *
       * <pre>
       *√‹¬Î
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tw.login.proto.CSLoginInfo)
    }

    static {
      defaultInstance = new CSLoginInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tw.login.proto.CSLoginInfo)
  }

  public interface CSLoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    boolean hasLoginInfo();
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    com.tw.login.proto.CsLogin.CSLoginInfo getLoginInfo();
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder getLoginInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.tw.login.proto.CSLoginReq}
   *
   * <pre>
   *∑¢ÀÕµ«¬º«Î«Û
   * </pre>
   */
  public static final class CSLoginReq extends
      com.google.protobuf.GeneratedMessage
      implements CSLoginReqOrBuilder {
    // Use CSLoginReq.newBuilder() to construct.
    private CSLoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSLoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSLoginReq defaultInstance;
    public static CSLoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public CSLoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.tw.login.proto.CsLogin.CSLoginInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = loginInfo_.toBuilder();
              }
              loginInfo_ = input.readMessage(com.tw.login.proto.CsLogin.CSLoginInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginInfo_);
                loginInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tw.login.proto.CsLogin.CSLoginReq.class, com.tw.login.proto.CsLogin.CSLoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<CSLoginReq> PARSER =
        new com.google.protobuf.AbstractParser<CSLoginReq>() {
      public CSLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;
    public static final int LOGININFO_FIELD_NUMBER = 1;
    private com.tw.login.proto.CsLogin.CSLoginInfo loginInfo_;
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    public boolean hasLoginInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    public com.tw.login.proto.CsLogin.CSLoginInfo getLoginInfo() {
      return loginInfo_;
    }
    /**
     * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
     */
    public com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder getLoginInfoOrBuilder() {
      return loginInfo_;
    }

    private void initFields() {
      loginInfo_ = com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLoginInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLoginInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, loginInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, loginInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tw.login.proto.CsLogin.CSLoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tw.login.proto.CSLoginReq}
     *
     * <pre>
     *∑¢ÀÕµ«¬º«Î«Û
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tw.login.proto.CsLogin.CSLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tw.login.proto.CsLogin.CSLoginReq.class, com.tw.login.proto.CsLogin.CSLoginReq.Builder.class);
      }

      // Construct using com.tw.login.proto.CsLogin.CSLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (loginInfoBuilder_ == null) {
          loginInfo_ = com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance();
        } else {
          loginInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginReq_descriptor;
      }

      public com.tw.login.proto.CsLogin.CSLoginReq getDefaultInstanceForType() {
        return com.tw.login.proto.CsLogin.CSLoginReq.getDefaultInstance();
      }

      public com.tw.login.proto.CsLogin.CSLoginReq build() {
        com.tw.login.proto.CsLogin.CSLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tw.login.proto.CsLogin.CSLoginReq buildPartial() {
        com.tw.login.proto.CsLogin.CSLoginReq result = new com.tw.login.proto.CsLogin.CSLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (loginInfoBuilder_ == null) {
          result.loginInfo_ = loginInfo_;
        } else {
          result.loginInfo_ = loginInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tw.login.proto.CsLogin.CSLoginReq) {
          return mergeFrom((com.tw.login.proto.CsLogin.CSLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tw.login.proto.CsLogin.CSLoginReq other) {
        if (other == com.tw.login.proto.CsLogin.CSLoginReq.getDefaultInstance()) return this;
        if (other.hasLoginInfo()) {
          mergeLoginInfo(other.getLoginInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginInfo()) {
          
          return false;
        }
        if (!getLoginInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tw.login.proto.CsLogin.CSLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tw.login.proto.CsLogin.CSLoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;
      private com.tw.login.proto.CsLogin.CSLoginInfo loginInfo_ = com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tw.login.proto.CsLogin.CSLoginInfo, com.tw.login.proto.CsLogin.CSLoginInfo.Builder, com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder> loginInfoBuilder_;
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public boolean hasLoginInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public com.tw.login.proto.CsLogin.CSLoginInfo getLoginInfo() {
        if (loginInfoBuilder_ == null) {
          return loginInfo_;
        } else {
          return loginInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder setLoginInfo(com.tw.login.proto.CsLogin.CSLoginInfo value) {
        if (loginInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginInfo_ = value;
          onChanged();
        } else {
          loginInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder setLoginInfo(
          com.tw.login.proto.CsLogin.CSLoginInfo.Builder builderForValue) {
        if (loginInfoBuilder_ == null) {
          loginInfo_ = builderForValue.build();
          onChanged();
        } else {
          loginInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder mergeLoginInfo(com.tw.login.proto.CsLogin.CSLoginInfo value) {
        if (loginInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              loginInfo_ != com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance()) {
            loginInfo_ =
              com.tw.login.proto.CsLogin.CSLoginInfo.newBuilder(loginInfo_).mergeFrom(value).buildPartial();
          } else {
            loginInfo_ = value;
          }
          onChanged();
        } else {
          loginInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public Builder clearLoginInfo() {
        if (loginInfoBuilder_ == null) {
          loginInfo_ = com.tw.login.proto.CsLogin.CSLoginInfo.getDefaultInstance();
          onChanged();
        } else {
          loginInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public com.tw.login.proto.CsLogin.CSLoginInfo.Builder getLoginInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLoginInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      public com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder getLoginInfoOrBuilder() {
        if (loginInfoBuilder_ != null) {
          return loginInfoBuilder_.getMessageOrBuilder();
        } else {
          return loginInfo_;
        }
      }
      /**
       * <code>required .com.tw.login.proto.CSLoginInfo LoginInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.tw.login.proto.CsLogin.CSLoginInfo, com.tw.login.proto.CsLogin.CSLoginInfo.Builder, com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder> 
          getLoginInfoFieldBuilder() {
        if (loginInfoBuilder_ == null) {
          loginInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tw.login.proto.CsLogin.CSLoginInfo, com.tw.login.proto.CsLogin.CSLoginInfo.Builder, com.tw.login.proto.CsLogin.CSLoginInfoOrBuilder>(
                  loginInfo_,
                  getParentForChildren(),
                  isClean());
          loginInfo_ = null;
        }
        return loginInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.tw.login.proto.CSLoginReq)
    }

    static {
      defaultInstance = new CSLoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tw.login.proto.CSLoginReq)
  }

  public interface CSLoginResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 result_code = 1;
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code com.tw.login.proto.CSLoginRes}
   *
   * <pre>
   *µ«¬º«Î«Ûªÿ∞¸ ˝æ›
   * </pre>
   */
  public static final class CSLoginRes extends
      com.google.protobuf.GeneratedMessage
      implements CSLoginResOrBuilder {
    // Use CSLoginRes.newBuilder() to construct.
    private CSLoginRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSLoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSLoginRes defaultInstance;
    public static CSLoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public CSLoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tw.login.proto.CsLogin.CSLoginRes.class, com.tw.login.proto.CsLogin.CSLoginRes.Builder.class);
    }

    public static com.google.protobuf.Parser<CSLoginRes> PARSER =
        new com.google.protobuf.AbstractParser<CSLoginRes>() {
      public CSLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSLoginRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSLoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 result_code = 1;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 result_code = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    private void initFields() {
      resultCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, resultCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, resultCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tw.login.proto.CsLogin.CSLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tw.login.proto.CsLogin.CSLoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tw.login.proto.CSLoginRes}
     *
     * <pre>
     *µ«¬º«Î«Ûªÿ∞¸ ˝æ›
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tw.login.proto.CsLogin.CSLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tw.login.proto.CsLogin.CSLoginRes.class, com.tw.login.proto.CsLogin.CSLoginRes.Builder.class);
      }

      // Construct using com.tw.login.proto.CsLogin.CSLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tw.login.proto.CsLogin.internal_static_com_tw_login_proto_CSLoginRes_descriptor;
      }

      public com.tw.login.proto.CsLogin.CSLoginRes getDefaultInstanceForType() {
        return com.tw.login.proto.CsLogin.CSLoginRes.getDefaultInstance();
      }

      public com.tw.login.proto.CsLogin.CSLoginRes build() {
        com.tw.login.proto.CsLogin.CSLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tw.login.proto.CsLogin.CSLoginRes buildPartial() {
        com.tw.login.proto.CsLogin.CSLoginRes result = new com.tw.login.proto.CsLogin.CSLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tw.login.proto.CsLogin.CSLoginRes) {
          return mergeFrom((com.tw.login.proto.CsLogin.CSLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tw.login.proto.CsLogin.CSLoginRes other) {
        if (other == com.tw.login.proto.CsLogin.CSLoginRes.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tw.login.proto.CsLogin.CSLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tw.login.proto.CsLogin.CSLoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 result_code = 1;
      private int resultCode_ ;
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 result_code = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tw.login.proto.CSLoginRes)
    }

    static {
      defaultInstance = new CSLoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tw.login.proto.CSLoginRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tw_login_proto_CSLoginInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tw_login_proto_CSLoginInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tw_login_proto_CSLoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tw_login_proto_CSLoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tw_login_proto_CSLoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tw_login_proto_CSLoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016cs_login.proto\022\022com.tw.login.proto\"1\n\013" +
      "CSLoginInfo\022\020\n\010UserName\030\001 \002(\t\022\020\n\010Passwor" +
      "d\030\002 \002(\t\"@\n\nCSLoginReq\0222\n\tLoginInfo\030\001 \002(\013" +
      "2\037.com.tw.login.proto.CSLoginInfo\"!\n\nCSL" +
      "oginRes\022\023\n\013result_code\030\001 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_tw_login_proto_CSLoginInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_tw_login_proto_CSLoginInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tw_login_proto_CSLoginInfo_descriptor,
              new java.lang.String[] { "UserName", "Password", });
          internal_static_com_tw_login_proto_CSLoginReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_tw_login_proto_CSLoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tw_login_proto_CSLoginReq_descriptor,
              new java.lang.String[] { "LoginInfo", });
          internal_static_com_tw_login_proto_CSLoginRes_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_tw_login_proto_CSLoginRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tw_login_proto_CSLoginRes_descriptor,
              new java.lang.String[] { "ResultCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
