// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_enum.proto

package com.tw.login.proto;

public final class CsEnum {
  private CsEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.tw.login.proto.EnmCmdID}
   */
  public enum EnmCmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CS_LOGIN_REQ = 10001;</code>
     *
     * <pre>
     *登录请求协议号
     * </pre>
     */
    CS_LOGIN_REQ(0, 10001),
    /**
     * <code>CS_LOGIN_RES = 10002;</code>
     *
     * <pre>
     *登录请求回包协议号
     * </pre>
     */
    CS_LOGIN_RES(1, 10002),
    ;

    /**
     * <code>CS_LOGIN_REQ = 10001;</code>
     *
     * <pre>
     *登录请求协议号
     * </pre>
     */
    public static final int CS_LOGIN_REQ_VALUE = 10001;
    /**
     * <code>CS_LOGIN_RES = 10002;</code>
     *
     * <pre>
     *登录请求回包协议号
     * </pre>
     */
    public static final int CS_LOGIN_RES_VALUE = 10002;


    public final int getNumber() { return value; }

    public static EnmCmdID valueOf(int value) {
      switch (value) {
        case 10001: return CS_LOGIN_REQ;
        case 10002: return CS_LOGIN_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnmCmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EnmCmdID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnmCmdID>() {
            public EnmCmdID findValueByNumber(int number) {
              return EnmCmdID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tw.login.proto.CsEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnmCmdID[] VALUES = values();

    public static EnmCmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EnmCmdID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tw.login.proto.EnmCmdID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcs_enum.proto\022\022com.tw.login.proto*0\n\010E" +
      "nmCmdID\022\021\n\014CS_LOGIN_REQ\020\221N\022\021\n\014CS_LOGIN_R" +
      "ES\020\222N"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
